server:
  port: 7077

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}/postgres
    username: postgres
    password: postgres
    hikari:
      schema: "order-manager"
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS "${spring.datasource.hikari.schema}"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

notification-manager:
  kafka:
    bootstrap-address: http://${KAFKA_HOST}